[package]
name = "bullet"
version = "0.1.0"
authors = ["Sebastian Köln <sebk@rynx.org>"]
build = "build.rs"
features = ["nvidia", "jit"]

[dependencies]
bullet_core   = { version = "0.1.0", path = "core" }
bullet_macros = { version = "0.1.0", path = "macros" }
cuda          = { version = "0.1",   path = "cuda", optional = true }
memmap        = { version = "0.5.2", optional=true }
simd          = { version = "0.2.0", optional=true }

[build-dependencies]
lalrpop = "0.13.1"

[features]
nvidia = ["cuda"]
jit = ["memmap", "simd"]
default = ["jit"]

[dev-dependencies]
jack = "0.5.3"
hound = "3.1.0"
termion = "1.5.1"
hiirc = "0.4.1"
simd = "0.2.0"
tuple = "0.3.3"
math_traits = "0.1.1"

[workspace]
members = ["core", "macros", "cuda"]
