[package]
name = "bullet"
version = "0.0.9"
authors = ["Sebastian Köln <sebk@rynx.org>"]
build = "build.rs"
features = ["nvidia"]

[dependencies]
tuple = { version = "0.3", features = ["impl_simd"] }
num = "*"
simd = "*"
lalrpop-util = "*"
regex = "*"
env_logger = "*"
itertools = "*"
quote = "*"
syn = "*"
memmap = "*"
cuda = { version = "0.1", path="cuda", optional=true }
math_traits = "*"

[features]
nvidia = ["cuda"]

[build-dependencies]
lalrpop = "*"

[dev-dependencies]
jack = "*"
hound = "*"
termion = "*"
hiirc = "*"

[workspace]
members = ["bullet_macros", "cuda"]
