[package]
name = "math"
version = "0.1.1"
authors = ["Sebastian Köln <sebk@rynx.org>"]
build = "build.rs"
features = ["nvidia"]

[dependencies]
tuple = { version = "0.3", features = ["impl_simd"], git="https://github.com/s3bk/tuple.git" }
num = "*"
simd = "*"
lalrpop-util = "*"
regex = "*"
env_logger = "*"
itertools = "*"
quote = "*"
syn = "*"
memmap = "*"
cuda = { git="https://github.com/s3bk/cuda.git", optional=true }
math_traits = "*"

[features]
nvidia = ["cuda"]

[build-dependencies]
lalrpop = "*"

[dev-dependencies]
jack = "*"
hound = "*"
termion = "*"
hiirc = "*"

[workspace]
members = ["math_macros"]
