[package]
name = "bullet"
version = "0.1.2"
authors = ["Sebastian Köln <sebk@rynx.org>"]
build = "build.rs"
features = ["nvidia", "jit"]
license = "MIT"
repository = "https://github.com/s3bk/bullet"
homepage = "https://github.com/s3bk/bullet"
categories = ["science"]
description = "Supersonic Math"

[dependencies]
memmap        = { version = "*", optional=true }
stdsimd       = { git = "https://github.com/rust-lang-nursery/stdsimd", optional=true }
tuple         = { git = "https://github.com/s3bk/tuple", features = ["impl_simd"] }
lalrpop-util  = "*"
regex         = "*"
itertools     = "*"
quote         = "*"
syn           = { version = "*", optional = true }
math_traits   = { git = "https://github.com/s3bk/math_traits" }

[build-dependencies]
lalrpop = "*"

[features]
nvidia = []
jit = ["memmap", "stdsimd"]
codegen = ["syn"]
default = ["jit"]

[dev-dependencies]
jack = "*"
hound = "*"
termion = "*"
hiirc = "*"
