[package]
name = "bullet"
version = "0.1.1"
authors = ["Sebastian Köln <sebk@rynx.org>"]
build = "build.rs"
features = ["nvidia", "jit"]
license = "MIT"
repository = "https://github.com/s3bk/bullet"
homepage = "https://github.com/s3bk/bullet"
categories = ["science"]
description = "Supersonic Math"

[dependencies]
memmap        = { version = "0.5.2", optional=true }
simd          = { version = "0.2.0", optional=true }
tuple         = { version = "0.3", features = ["impl_simd"] }
lalrpop-util  = "0.13.1"
regex         = "0.2.2"
env_logger    = "0.4.3"
itertools     = "0.6.3"
quote         = "0.3.15"
syn           = "0.11.11"
math_traits   = "0.1.1"

[build-dependencies]
lalrpop = "0.13.1"

[features]
nvidia = []
jit = ["memmap", "simd"]
default = ["jit", "nvidia"]

[dev-dependencies]
jack = "0.5.3"
hound = "3.1.0"
termion = "1.5.1"
hiirc = "0.4.1"
math_traits = "0.1.1"
