[package]
name = "bullet_macros"
version = "0.1.0"
authors = ["Sebastian Köln <sebk@rynx.org>"]

[dependencies]
simd = "*"

[dependencies.bullet_core]
path = "../core"
version = "0.1.0"

[lib]
proc-macro = true